fix_seed: 0
checkpoints_every: 2000
tensorboard_log: True
result_path: ./results/test

resume:
  resume: False
  resume_path: testadapterh_12tuneall_sgdlr001mixlenpad_esmpool2/checkpoints/checkpoint_0040000.pth
  restart_optimizer: True

model:
  compile_model: False
  struct_encoder:
    use_rotary_embeddings: True
    rotary_mode: 2 #1: d1-d2 2: edge_index 3:edge_index+E_vectors
    use_foldseek: False #this is used to control use foldseek as scalar
    use_foldseek_vector: True #use foldseek as vector
    gvp_num_layers: 3
    top_k: 30 #default 30 The number of edges to draw per node (as destination node).
    num_rbf: 16   #default 16
    num_positional_embeddings: 16  #default 16
    node_h_dim: (100,32) #default (100,32)
    edge_h_dim: (32,1)   #default (32,1)
    use_seq:
       enable: False
       seq_embed_mode: "embedding" #"embedding","ESM2"
       seq_embed_dim: 20 #1280 for ESM2

train_settings:
  data_path: /data/duolin/swiss-pos-512-gvp_splitdata/val/
  num_steps: 10000
  shuffle: True
  mixed_precision: "no" # no, fp16, bf16, fp8
  batch_size: 10
  residue_batch_size: 2000
  num_workers: 1
  gradient_accumulation: 1
  n_views: 2
  temperature: 0.05
  plddt_weight: False
  device: cuda



optimizer:
  name: adam
  lr: 8e-5
  weight_decouple: True
  weight_decay: 0.01
  eps: 1e-16
  beta_1: 0.9
  beta_2: 0.999
  use_8bit_adam: False
  grad_clip_norm: 1
  decay:
    warmup: 50
    min_lr: 1e-6
    gamma: 1
    first_cycle_steps: 20000

