fix_seed: 0
checkpoints_every: 1024
tensorboard_log: True
tqdm_progress_bar: False
result_path: ./results/gcpnet_vqvae/hp_test
normalizer_path: ./data/normalizer.pkl

resume:
  resume: False
  resume_path: results/gcpnet_vqvae/hp_test/2024-11-19__19-40-07/checkpoints/best_valid.pth
  restart_optimizer: True

model:
  compile_model: False
  max_length: 256
  encoder:
    name: gcpnet # gvp_transformer, gcpnet
    pretrained:
      enabled: True
      config_path: ./configs/pretrained/structure_denoising_pretrained_config.yaml
      checkpoint_path: ./models/checkpoints/structure_denoising/gcpnet/ca_bb/last.ckpt # define your checkpoint directory here
  decoder: geometric_decoder # geometric_decoder, gcpnet
  vqvae:
    vector_quantization:
      dim: 128
      decay: 0.8
      codebook_size: 256
      commitment_weight: 1.0
      alpha: 1.0
    encoder:
      dimension: 128
      num_heads: 16
      num_blocks: 4
    decoder:
      dimension: 128
      num_heads: 16
      num_blocks: 8

train_settings:
  data_path: /bml/acmwhb/Repositories/Lab_Repositories/vq_encoder_decoder/data/validation/validation_set_1024_h5
  num_epochs: 256
  shuffle: True
  loss: crossentropy
  sample_weight: False
  mixed_precision: fp16 # no, fp16, bf16, fp8
  save_pdb_every: 32
  batch_size: 32
  num_workers: 8
  grad_accumulation: 4
  max_task_samples: 16000
  losses:
    kabsch:
      enable: True
      weight: 0.05
    backbone_distance:
      enable: True
      weight: 10.0
    backbone_direction:
      enable: True
      weight: 10.0
    binned_distance_classification:
      enable: True
      weight: 10.0
    binned_direction_classification:
      enable: True
      weight: 10.0
    inverse_folding:
      enable: False
      weight: 1.0

valid_settings:
  data_path: /bml/acmwhb/Repositories/Lab_Repositories/vq_encoder_decoder/data/validation/validation_set_1024_h5
  do_every: 1
  save_pdb_every: 256
  batch_size: 16
  num_workers: 2

visualization_settings:
  data_path: /bml/acmwhb/Repositories/Lab_Repositories/vq_encoder_decoder/data/validation/validation_set_1024_h5
  fasta_path: ../../visualization/Rep_subfamily_basedon_S40pdb.fa
  do_every: 4096
  batch_size: 1
  num_workers: 4

optimizer:
  name: schedulerfree
  lr: 8e-5
  weight_decouple: True
  weight_decay: 1e-2
  eps: 1e-16
  beta_1: 0.9
  beta_2: 0.999
  use_8bit_adam: False
  grad_clip_norm: 1
  decay:
    warmup: 1024
    min_lr: 1e-7
    gamma: 0.2
    num_restarts: 1