fix_seed: 0
checkpoints_every: 1024
tensorboard_log: True
tqdm_progress_bar: False
result_path: ./results/gcpnet_vqvae/
normalizer_path: ./data/normalizer.pkl

resume:
  resume: False
  resume_path: results/gcpnet_vqvae/2025-03-15__02-07-15/checkpoints/epoch_1024.pth
  restart_optimizer: True

model:
  compile_model: False
  max_length: 128
  encoder:
    name: gcpnet # gvp_transformer, gcpnet
    pretrained:
      enabled: True
      config_path: ./configs/pretrained/structure_denoising_pretrained_config.yaml
      checkpoint_path: ./models/checkpoints/structure_denoising/gcpnet/ca_bb/last.ckpt # define your checkpoint directory here
  decoder: geometric_decoder # geometric_decoder, gcpnet
  vqvae:
    vector_quantization:
      dim: 768
      decay: 0.8
      codebook_size: 256
      commitment_weight: 1.0
      alpha: 1.0
    encoder:
      dimension: 768
      num_heads: 16
      num_blocks: 8
    decoder:
      dimension: 768
      num_heads: 16
      num_blocks: 4

train_settings:
  data_path: /mnt/hdd8/mehdi/datasets/vqvae/swissprot_1024_h5
  num_epochs: 1024
  shuffle: True
  loss: crossentropy
  sample_weight: False
  mixed_precision: fp16 # no, fp16, bf16, fp8
  save_pdb_every: 16
  batch_size: 32
  num_workers: 8
  grad_accumulation: 1
  max_task_samples: 64000
  gradient_norm_logging_freq: 50  # How often to calculate and log gradient norm (in steps)
  losses:
    alignment_strategy: kabsch # kabsch, kabsch_old, quaternion
    mse:
      enable: True
      weight: 1.0
    backbone_distance:
      enable: False
      weight: 1.0
    backbone_direction:
      enable: False
      weight: 1.0
    binned_distance_classification:
      enable: False
      weight: 1.0
    binned_direction_classification:
      enable: False
      weight: 1.0
    inverse_folding:
      enable: False
      weight: 1.0
    fape:
      enable: False
      weight: 1.0
      clamp_distance: 10.0
      length_scale: 10.0

valid_settings:
  data_path: /mnt/hdd8/mehdi/datasets/vqvae/validation_set_1024_h5
  do_every: 16
  save_pdb_every: 16
  batch_size: 16
  num_workers: 2

visualization_settings:
  data_path: /mnt/hdd8/mehdi/datasets/vqvae/validation_set_1024_h5
  fasta_path: ../../visualization/Rep_subfamily_basedon_S40pdb.fa
  do_every: 8192
  batch_size: 1
  num_workers: 4

optimizer:
  name: schedulerfree
  lr: 5e-5
  weight_decouple: True
  weight_decay: 1e-2
  eps: 1e-16
  beta_1: 0.9
  beta_2: 0.999
  use_8bit_adam: False
  grad_clip_norm: 1
  decay:
    warmup: 1024
    min_lr: 1e-7
    gamma: 0.2
    num_restarts: 1
