fix_seed: 0
checkpoints_every: 8
tensorboard_log: True
tqdm_progress_bar: True
result_path: ./results

resume:
  resume: False
  resume_path: ./path/to/checkpoint.pth
  restart_optimizer: True
  handle_shape_missmatch: False

model:
  compile_model: False

  encoder:
    dimension: 480
    dim_feedforward: 960
    num_heads: 8
    num_layers: 8
    max_len: 512
    activation_function: gelu

  vector_quantization:
    dim: 16
    codebook_size: 32
    decay: 0.9
    commitment_weight : 0.9
    alpha: 2.0

  decoder:
    dimension: 480
    dim_feedforward: 960
    num_heads: 8
    num_layers: 8
    max_len: 512
    activation_function: gelu

train_settings:
  data_path: H:\Datasets\Joint_training
  num_epochs: 32
  shuffle: True
  loss: crossentropy
  sample_weight: True
  mixed_precision: fp16 # no, fp16, bf16, fp8
  device: cuda
  batch_size: 128
  num_workers: 12
  grad_accumulation: 1
  max_task_samples: 50000

valid_settings:
  data_path: H:\Datasets\Joint_training
  do_every: 1
  batch_size: 8
  device: cuda
  num_workers: 0

optimizer:
  name: adam
  lr: 1e-3
  weight_decouple: True
  weight_decay: 1e-2
  eps: 1e-16
  beta_1: 0.9
  beta_2: 0.999
  use_8bit_adam: False
  grad_clip_norm: 1
  decay:
    warmup: 0
    min_lr: 1e-5
    gamma: 0.2
    num_restarts: 1