trained_model_dir: "results/gcpnet_vqvae/2025-06-02__20-35-00"
checkpoint_path: "checkpoints/best_valid.pth"
config_vqvae: "config_vqvae.yaml"
config_encoder: "config_gcpnet_encoder.yaml"
config_decoder: "config_geometric_decoder.yaml"
data_path: "path/to/inference/h5/data"
output_base_dir: "inference_results"
batch_size: 16
shuffle: True
num_workers: 0
max_task_samples: 1000
tqdm_progress_bar: True
return_vq_layer: False
alignment_strategy: "kabsch"  # kabsch, kabsch_old, quaternion, no
save_original_pdb: True # whether to save original pdbs
mixed_precision: "bf16"  # no, fp16, bf16, fp8
