checkpoint_dir: "results/2024-06-25__10-07-10/checkpoints/"
batch_size: 1
output_dir: "inference_results"
tqdm_progress_bar: True

contact_map_settings:
  threshold: 8
  protein_dir: "/home/renjz/data/swissprot_1024_h5"

model:
  compile_model: False
  num_layers: 4
  max_length: 128

  encoder:
    dim: 8

  vector_quantization:
    dim: 16
    codebook_size: 512
    decay: 0.9
    commitment_weight : 0.9
    alpha: 2.0
    lfq: False

  decoder:
    dim: 8

train_settings:
  data_path: /home/renjz/data/swissprot_1024_h5/
  num_epochs: 32
  shuffle: True
  mixed_precision: fp16 # no, fp16, bf16, fp8
  batch_size: 128
  num_workers: 8
  grad_accumulation: 1

  max_task_samples: 100000
  cutout:
    enable: False
    min_mask_size: 1
    max_mask_size: 30
    max_cuts: 4

valid_settings:
  data_path: /home/renjz/data/cath_4_3_0/
  do_every: 1
  shuffle: True
  batch_size: 128
  num_workers: 8

visualization_settings:
  data_path: /home/renjz/data/cath_4_3_0/
  fasta_path: visualization/Rep_subfamily_basedon_S40pdb.fa
  do_every: 4
  batch_size: 1
  num_workers: 2

optimizer:
  name: adam
  lr: 0.01
  weight_decouple: True
  weight_decay: 1e-2
  eps: 1e-16
  beta_1: 0.9
  beta_2: 0.999
  use_8bit_adam: False
  grad_clip_norm: 1
  decay:
    warmup: 0
    min_lr: 1e-5
    gamma: 0.2
    num_restarts: 1