trained_model_dir: "results/gcpnet_vqvae/2025-06-02__20-35-00"
checkpoint_path: "checkpoints/best_valid.pth"
config_vqvae: "config_vqvae.yaml"
config_encoder: "config_gcpnet_encoder.yaml"
config_decoder: "config_geometric_decoder.yaml"
data_path: "path/to/inference/h5/data"
output_base_dir: "inference_results"
batch_size: 16
shuffle: True
num_workers: 0
max_task_samples: 5000000
tqdm_progress_bar: True
return_vq_layer: True
vq_indices_csv_filename: "vq_indices.csv"  # Name of the CSV file for VQ indices if return_vq_layer is True
alignment_strategy: "kabsch"  # kabsch, kabsch_old, quaternion, no
save_original_pdb: False # whether to save original pdbs only works if return_vq_layer is False
mixed_precision: "bf16"  # no, fp16, bf16, fp8
