trained_model_dir: "path/to/trained_model"  # Directory where the trained model is saved
checkpoint_path: "checkpoints/best_valid.pth"
config_vqvae: "config_vqvae.yaml"
config_encoder: "config_gcpnet_encoder.yaml"
config_decoder: "config_geometric_decoder.yaml"

output_base_dir: "inference_codebook_extraction_results"

codebook_h5_filename: "codebook_embeddings.h5"
