trained_model_dir: "results/gcpnet_vqvae/2025-06-02__20-35-00"
checkpoint_path: "checkpoints/best_valid.pth"
config_vqvae: "config_vqvae.yaml"
config_encoder: "config_gcpnet_encoder.yaml"
config_decoder: "config_geometric_decoder.yaml"
data_path: "/home/renjz/data/swissprot_1024_h5"
output_base_dir: "inference_results"
batch_size: 1
num_workers: 0
max_task_samples: 1000
max_length: 128
tqdm_progress_bar: True

