trained_model_dir: "results/dgx/vqvae/2025-07-19__20-09-19"
checkpoint_path: "checkpoints/best_valid.pth"
config_vqvae: "config_vqvae.yaml"
config_encoder: "config_gcpnet_encoder.yaml"
config_decoder: "config_geometric_decoder.yaml"

data_path: "/mnt/hdd8/farzaneh/datasets/PST_remote_homology_h5/"
output_base_dir: "inference_embed_results"

batch_size: 64
shuffle: True
num_workers: 0
max_task_samples: 5000000
vq_embeddings_h5_filename: "vq_embed.h5"
mixed_precision: "bf16"  # no, fp16, bf16, fp8

tqdm_progress_bar: True
