trained_model_dir: "path/to/trained_model"  # Directory where the trained model is saved
checkpoint_path: "checkpoints/best_valid.pth"
config_vqvae: "config_vqvae.yaml"
config_encoder: "config_gcpnet_encoder.yaml"
config_decoder: "config_geometric_decoder.yaml"

indices_csv_path: "path/to/vq_indices.csv"
output_base_dir: "inference_decode_results"

batch_size: 16
shuffle: True
num_workers: 0
max_task_samples: 5000000
mixed_precision: "bf16"  # no, fp16, bf16, fp8

tqdm_progress_bar: True

compile_model:
  enabled: false
  mode: null
  backend: inductor
  compile_encoder: false
