trained_model_dir: "path/to/trained_model"  # Directory where the trained model is saved
checkpoint_path: "checkpoints/best_valid.pth"
config_vqvae: "config_vqvae.yaml"
config_encoder: "config_gcpnet_encoder.yaml"
config_decoder: "config_geometric_decoder.yaml"

data_path: "path/to/inference/h5/data"
output_base_dir: "inference_embed_results"

batch_size: 16
shuffle: True
num_workers: 0
max_task_samples: 5000000
vq_embeddings_h5_filename: "vq_embed.h5"
mixed_precision: "bf16"  # no, fp16, bf16, fp8

tqdm_progress_bar: True
